export const translates = {
  navigation: {
    home: 'Vítejte',
    grocery: 'Hledat podle ingrediencí',
    recipes: 'Recepty',
    recipe: 'Recept',
    features: 'Funkce',
    profile: 'Nastavení',
    cart: 'Nákupní košík',
    voice: 'Hlas',
    storage: 'Úložiště',
    subscriptions: 'Podpora',
    faq: 'FAQ',
    author: 'Šéfkuchař',
    authors: 'Kuchaři',
  },
  common: {
    close: 'Zavřít',
    hour: 'hodina',
    hours: 'hodiny',
    minute: 'minuta',
    minutes: 'minuty',
    second: 'sekunda',
    seconds: 'sekundy',
  },
  pages: {
    authors: {
      emptyList: 'Na platformě nebyli nalezeni žádní autoři :(',
      becomeChef: 'Staňte se novým šéfkuchařem',
    },
    author: {
      emptyList: 'Autor nemá žádné recepty :(',
      recipes: 'Recepty:',
      title: 'Naše milé hvězdy',
    },
    cart: {
      notFound: 'Nyní je prázdný, můžete přidat položky z jakékoli stránky receptu',
      notFoundButton: 'Přejít na recepty',
      finish: 'Dokončit nákup',
      addIngredient: 'Přidat svůj produkt ...',
      removeSelectedItem: 'Odebrat vybrané položky',
      addedToCartTitle: '"{name}" bylo přidáno do košíku. Najdete ho v hlavním menu',
      alreadyAdded: '"{name}" již v košíku',
      finishShopping: 'Nákup je ukončen, děkujeme',
      onBoardingTooltip: 'Vyberte všechny položky pro dokončení nákupu',
      howItWorks: 'Nákupní košík \n - Jak to funguje -',
      clear: 'Chcete vyprázdnit celý košík?',
    },
    welcome: {
      tryIt: 'Recepty!',
      title: 'Začněte svou cestu ke zlepšení vaření přímo z domova.',
      subTitle: 'Vyzkoušejte AI hlasového asistenta na stránce receptu',
      generator: 'Přejeďte a získejte náhodný recept',
    },
    grocery: {
      startVoice: 'Použijte hlas pro rozpoznání',
      onBoard: 'Vyberte více než 3 ingredience pro pokračování',
      selectText: 'Vyberte produkty',
      name: 'Název',
      confirmText: 'Získat recepty',
      removeAll: 'Odstranit vše!',
      applyText: 'Použít',
      features: 'Nastavte své gastrointestinální vlastnosti',
      yes: 'Ano',
      no: 'Ne',
      productAdded: 'Identifikovali jsme {count} produktů:',
      productNotFound: 'Omlouváme se, nerozpoznali jsme žádné ingredience',
      addedIngredient: 'Přidáno "{name}", řekněte další',
      tellUs: 'Řekněte nám, jaké máte ingredience ...',
      search: 'Hledejte zde ...',
      notFound: 'Omlouváme se, nic jsme nenašli. Zkuste to znovu',
      ok: 'Ok',
      howItWorks: 'Hledání podle ingrediencí \n - Jak to funguje -',
      assistantHelpTitle: 'Bezrucní výběr ingrediencí',
      assistantHelpTextButton: 'Ok',
      assistantHelpText: 'Stačí klepnout na tlačítko v horní části seznamu a můžete použít hlas k přidání položek z mrazničky. Až budete hotovi, znovu ho stiskněte a zobrazí se výsledek!',
    },
    profile: {
      terms: 'Podmínky použití 📄',
      privacy: 'Soukromí 📃',
      text: 'Máte možnost vybrat své gastro preference',
      footer: 'Tým Gastro&Me Ⓒ 2023',
      chooseNewVoice: 'Ahoj! Jsem váš nový asistent',
      chooseAssistantButton: 'Hlas asistenta 🗣',
      confirmText: 'Potvrdit',
      contact: 'Kontaktujte nás 📩',
      subscribed: 'Aktuální plán: {name}',
      firstSeen: 'S námi od: {date}',
      expires: 'Vyprší: {date}',
      subscriptions: 'Podpora 🙏',
      measure: 'Měření',
      chooseSubscription: 'Vyberte plán podpory',
      subscriptionsTitle: 'Předplatné',
      howToCancel: 'Spravujte své předplatné',
      cancel: 'Zrušit',
      inActiveSubscriberTitle: 'Vaše podpora pro nás znamená svět 🫡',
      storage: 'Úložiště',
      feedback: 'Ohodnoťte aplikaci 🤩'
    },
    storage: {
      usedSize: 'Použitá velikost - {size} Mb',
      clean: 'Vyčistit',
      sure: 'Jste si jisti, že chcete vymazat všechny soubory aplikace?',
      cleanTitle: 'Úložiště je vyčištěno',
      cleanDescription: 'Smazali jsme videa a fotografie, které aplikace uchovávala',
      ok: 'Ok'
    },
    recipes: {
      get: 'Číst dál',
      voiceAssistant: 'Hledání ingrediencí',
      onBoardingTooltip: 'Zkuste filtrovat podle kategorie',
      searchTitle: 'Hledat podle názvu ...',
      selectedIngredientsTitle: 'Hledáte podle těchto ingrediencí',
      selectedIngredients: 'Máte:',
      reset: 'Obnovit',
      emptyList: 'Omlouváme se, nemáme pro vás vhodné recepty',
      hasVideoSteps: 'Zahrnuje video instrukce',
      filters: 'Filtry',
      ingredients: 'Ingredience',
      sort: 'Třídit',
      favorites: 'Uložené',
      filtersTitle: 'Můžete vybrat kategorie pro filtrování receptů:',
      onBoardingFilter: 'Filtry najdete zde',
      close: 'Zavřít',
      apply: 'Použít',
      subscriptions: 'Připravené plány pro vás:',
      buySubscription: 'Předplatit více receptů',
      extraRecipesText: 'Máte 7 měsíčních receptů zdarma,\n chcete více?',
      time: '{time} min',
    },
    recipe: {
      time: '{time} min',
      step: 'Krok {number}.',
      start: 'Začít',
      startVoice: 'Začněte vařit!',
      addedToCartTitle: '"{name}" bylo přidáno do košíku',
      addedToCartText: 'Tyto ingredience najdete v košíku pro snadný nákup',
      cartButton: 'Navštivte košík',
      level: 'Úroveň',
      region: 'Region',
      author: 'Šéfkuchař: {name}',
      cartOnBoard: 'Přidejte všechny ingredience do nákupního košíku',
      servings: 'Porce: {count} osob',
      watchVideo: 'Otevřít video kroky',
      voiceSelect: 'Vyberte hlas',
      ingredients: 'Ingredience',
      addToCart: 'Stiskněte pro přidání všech ingrediencí do nákupního seznamu',
      viewed: 'Zhlédnuto',
      chooseMeasure: 'Měření ⚖️',
    },
    cooking: {
      singleVideo: '\n (Jedno video pro všechny kroky)',
      step: '- Krok {index} z {count} -',
      startVoice: 'Vařte s asistentem',
      assistantCommandsTitle: 'Použijte příkazy "další", "zpět", "opakovat" a "časovač" pro interakci s hlasovým asistentem',
      start: 'Začít',
      madeBy: 'Video Instagram @{name}',
      loading: 'Stahování videa...',
      voiceSelect: 'Hlasy',
      lastStep: ', Toto je poslední krok, použijte příkaz "Hotovo" pro ukončení vaření',
      timerEnd: 'Časovač skončil',
      nextCommand: 'Čekám na váš příkaz',
      durationCommand: 'Pro nastavení časovače na {duration}, řekněte časovač.',
      voiceCommands: 'Příkazy: další, zpět, opakovat nebo časovač',
      listenText: 'Poslech popisu kroku ...',
      back: 'Zpět',
      "next": "další",
      "repeat": "opakovat",
      "timer": "časovač",
      "done": "hotovo",
    }
  },
  components: {
    autocomplete: {
      applyText: 'Použít',
      removeAll: 'Obnovit!',
    },
    modal: {
      close: 'Zavřít',
    },
    subscriptionsModal: {
      free: 'Udržet zdarma',
      benefits: 'Exkluzivní výhody na vás čekají:',
      benefitsOne: 'Odemkněte 30+ video receptů 🌟',
      benefitsTwo: 'Podpořte projekt bez reklam 🙏',
      benefitsThree: 'Pravidelně čerstvé recepty 📅',
      error: 'Omlouváme se, chyba při nákupu předplatného, zkuste to znovu nebo nás kontaktujte na stránce nastavení',
      restore: 'Obnovit',
      success: 'Děkujeme za předplatné! Vaše podpora podporuje růst naší aplikace 🚀',
    },
    voicePermission: {
      text: 'Ups!\n\n Hlasový asistent vyžaduje oprávnění pro "Mikrofon" a "Rozpoznávání řeči". \n\n Zkuste navštívit nastavení aplikace a zapnout ho.',
      button: 'Přejít do nastavení',
      close: 'Zavřít',
    },
    voiceButton: {
      listenActive: 'Naslouchám...',
    },
    volumeModal: {
      text: 'Ups! Vypadá to, že váš zvuk je příliš nízký. Zvyšte ho pro přístup k této funkci.',
      tryAgain: 'Zkusit znovu',
      close: 'Zavřít',
    },
    recipesGenerator: {
      title: 'Náhodný recept zde:',
      extraRecipesText: 'Máte k dispozici 7 receptů, pokud chcete více, klikněte na text',
      generate: 'Získat nový',
      time: '{time} min',
    },
    measuresModal: {
      title: 'Vyberte typ váhy pro vaši zemi',
      close: 'Zavřít',
      oz: 'Imperiální',
      g: 'Metrické',
      tbsp: 'Polévková lžíce',
    },
    timerButton: {
      buttonText: 'Časovač: {duration}'
    },
  }
};
