export const translates = {
  navigation: {
    home: 'Vítejte',
    grocery: 'Vyhledávání podle ingrediencí',
    recipes: 'Recepty',
    recipe: 'Recept',
    features: 'Funkce',
    profile: 'Nastavení',
    cart: 'Nákupní košík',
    voice: 'Hlas',
    storage: 'Úložiště',
    subscriptions: 'Podpora',
    faq: 'FAQ',
    author: 'Kuchař',
    authors: 'Gastro Kuchaři',
  },
  common: {
    close: 'Zavřít',
    hour: 'hodina',
    hours: 'hodiny',
    minute: 'minuta',
    minutes: 'minuty',
    second: 'sekunda',
    seconds: 'sekundy',
  },
  pages: {
    authors: {
      emptyList: 'Na platformě nebyli nalezeni žádní autoři :(',
      becomeChef: "Stát se novým Kuchařem",
    },
    author: {
      emptyList: 'Autor nemá žádné recepty :(',
      recipes: 'Recepty:',
      title: "Naše milované hvězdy",
    },
    cart: {
      notFound: 'Košík je prázdný, můžete přidat položky z jakékoli stránky receptu',
      notFoundButton: 'Přejít na Recepty',
      finish: 'Dokončit nákup',
      addIngredient: 'Přidat váš produkt ...',
      removeSelectedItem: 'Odstranit vybrané položky',
      addedToCartTitle: '"{name}" byl přidán do košíku. Najdete ho v hlavním menu',
      alreadyAdded: '"{name}" je již v košíku',
      finishShopping: "Nákup je ukončen, děkujeme vám",
      onBoardingTooltip: 'Vyberte všechny položky pro dokončení nákupu',
      howItWorks: 'Nákupní košík \n - Jak to funguje -',
      clear: 'Chcete vymazat celý košík?',
    },
    welcome: {
      tryIt: 'Seznam!',
      title: 'Začněte svou cestu ke zlepšení vaření přímo z domova.',
      subTitle: 'Vyzkoušejte asistenta vaření s hlasovým ovládáním na stránce receptu',
      generator: 'Posuňte a získáte náhodný recept',
    },
    grocery: {
      startVoice: 'Použijte hlas pro detekci',
      onBoard: 'Vyberte více než 3 položky pro pokračování',
      selectText: 'Vyberte produkty',
      name: 'Název',
      confirmText: 'Získat recepty',
      removeAll: 'Odstranit vše!',
      applyText: 'Použít',
      features: 'Nastavit gastrointestinální funkce',
      yes: 'Ano',
      no: 'Ne',
      productAdded: 'Bylo rozpoznáno {count} produktů:',
      productNotFound: 'Omlouváme se, nebyly rozpoznány žádné ingredience',
      addedIngredient: 'Přidán "{name}", řekněte další',
      tellUs: 'Řekněte nám, jaké ingredience máte ...',
      search: 'Vyhledat zde ...',
      notFound: 'Omlouváme se, nemůžeme najít nic. Zkuste to prosím znovu',
      ok: 'Ok',
      howItWorks: 'Vyhledávání podle ingrediencí \n - Jak to funguje -',
      assistantHelpTitle: 'Bezdotykový výběr ingrediencí',
      assistantHelpTextButton: 'Ok',
      assistantHelpText: 'Stačí klepnout na tlačítko nahoře v seznamu a můžete pomocí hlasu přidávat položky z vašeho mrazáku. Až budete hotovi, znovu jej stiskněte a zobrazí se výsledek!',
    },
    profile: {
      terms: 'Podmínky použití',
      privacy: 'Soukromí',
      text: 'Máte možnost zvolit své gastro preference',
      footer: 'Tým Gastro&Me Ⓒ 2023',
      chooseNewVoice: 'Ahoj! Já jsem váš nový asistent',
      chooseAssistantButton: 'Hlas asistenta 🗣',
      confirmText: 'Potvrdit',
      contact: 'Kontaktujte nás 📩',
      subscribed: 'Současný plán je: {name}',
      firstSeen: 'Jste s námi od: {date}',
      expires: 'Platnost vyprší: {date}',
      subscriptions: 'Připojte se ke komunitě 🌟',
      measure: 'Měřit ',
      chooseSubscription: 'Vyberte plán podpory',
      subscriptionsTitle: 'Předplatné',
      howToCancel: 'Spravovat vaše předplatné',
      cancel: 'Zrušit',
      inActiveSubscriberTitle: 'Vaše podpora pro nás znamená svět 🫡',
      storage: 'Úložiště',
      feedback: 'Ohodnoťte aplikaci 🤩'
    },
    storage: {
      usedSize: 'Použitá velikost - {size} Mb',
      clean: 'Vyčistit',
      sure: 'Jste si jisti, že chcete vymazat všechny soubory aplikace?',
      cleanTitle: 'Úložiště je vyčištěno',
      cleanDescription: 'Byly odstraněny videa a fotky, které aplikace uchovávala',
      ok: 'Ok'
    },
    recipes: {
      get: 'Přečíst více',
      voiceAssistant: 'Vyhledávání podle ingrediencí',
      onBoardingTooltip: 'Vyzkoušejte filtrování podle kategorií',
      searchTitle: 'Hledat podle názvu ...',
      selectedIngredientsTitle: 'Vyhledáváte podle těchto ingrediencí',
      selectedIngredients: 'Máte:',
      reset: 'Resetovat',
      emptyList: 'Omlouváme se, pro vás nejsou žádné vhodné recepty',
      hasVideoSteps: 'Obsahuje video instrukci',
      filters: 'Filtry',
      ingredients: 'Ingredience',
      sort: 'Řazení',
      favorites: 'Uložené',
      filtersTitle: 'Můžete si vybrat kategorie pro filtrování receptů: ',
      onBoardingFilter: 'Filtry najdete zde',
      close: 'Zavřít',
      apply: 'Použít',
      subscriptions: 'Připravené plány pro vás:',
      buySubscription: 'Připojte se ke komunitě!',
      extraRecipesText: 'Máte 8 volných měsíčních receptů,\n přejete si více?',
      time: '{time} min',
    },
    recipe: {
      time: '{time} min',
      step: 'Krok {number}.',
      start: 'Začít',
      startVoice: 'Začněte vařit!',
      addedToCartTitle: '"{name}" byl přidán do košíku',
      addedToCartText: 'Tyto ingredience najdete v košíku, aby byl nákup snadný',
      cartButton: 'Navštívit košík',
      level: 'Úroveň',
      region: 'Region',
      author: 'Kuchař: {name}',
      cartOnBoard: 'Přidat všechny ingredience do nákupního košíku',
      servings: 'Porce: {count} lidí',
      watchVideo: 'Otevřít video kroky',
      voiceSelect: 'Vybrat hlas',
      ingredients: 'Ingredience',
      addToCart: 'Stiskněte pro přidání všech ingrediencí do nákupního seznamu',
      viewed: 'Zobrazeno',
      chooseMeasure: 'Měřit ⚖️',
    },
    cooking: {
      singleVideo: '(Jedno video pro všechny kroky)',
      step: '- Krok {index} z {count} -',
      startVoice: 'Vařte s asistentem',
      assistantCommandsTitle: 'Použijte příkazy "další", "zadní", "opakovat" pro interakci s hlasovým asistentem',
      start: 'Začít',
      madeBy: 'Video Instagram @{name}',
      loading: 'Stahování videa...',
      voiceSelect: 'Hlasy',
      lastStep: ', To je poslední krok, použijte příkaz "Hotovo" pro ukončení vaření',
      timerEnd: 'Váš časovač skončil',
      nextCommand: 'Čekám na váš příkaz',
      durationCommand: 'Pro nastavení časovače na {duration}, řekněte časovač.',
      voiceCommands: 'Příkazy: další, zadní, opakovat nebo časovač',
      listenText: 'Poslouchejte krok ...',
      "next": "další",
      "repeat": "opakovat",
      "timer": "časovač",
      "done": "hotovo",
      back: 'Zadní',
      backCommand: 'zadní',
    }
  },
  components: {
    filters: {
      'breakfast': 'Snídaně',
      'lunch': 'Oběd',
      'dinner': 'Večeře',

      'italy': 'Itálie',
      'ukraine': 'Ukrajina',

      'pasta': 'Těstoviny',
      'dessert': 'Dezert',
      'snack': 'Svačina',
      'coffee': 'Káva',
      'salad': 'Salát',
    },
    autocomplete: {
      applyText: 'Použít',
      removeAll: 'Reset!',
    },
    modal: {
      close: 'Zavřít',
    },
    subscriptionsModal: {
      free: 'Zůstat zdarma',
      benefits: 'Exkluzivní výhody komunity GastroMe:',
      benefitsOne: 'Odemkněte 30+ receptů 📚',
      benefitsTwo: 'Speciální prostředí 🥰',
      benefitsThree: 'Soukromé streamy 🧝 (soon)',
      error: 'Omlouváme se, došlo k chybě při nákupu předplatného, zkuste to znovu nebo nás kontaktujte na stránce nastavení',
      restore: 'Obnovit',
      success: 'Děkujeme za předplatné! Vaše podpora pohání růst naší aplikace 🚀',
    },
    voicePermission: {
      text: 'Jejda!\n\n  AI Asistent vyžaduje oprávnění pro "Mikrofon" a "Rozpoznávání řeči". \n\n  Zkuste navštívit nastavení aplikace pro jejich zapnutí.',
      button: 'Přejít do nastavení',
      close: 'Zavřít',
    },
    voiceButton: {
      listenActive: 'Poslouchám...',
    },
    volumeModal: {
      text: 'Jejda! Vypadá to, že váš zvuk je nízký. Zvyšte hlasitost pro přístup k této funkci.',
      tryAgain: 'Zkusit znovu',
      close: 'Zavřít',
    },
    recipesGenerator: {
      title: 'Náhodný recept zde:',
      extraRecipesText: 'K dispozici máte 8 receptů, pro více klikněte na text',
      generate: 'Získat nový',
      time: '{time} min',
    },
    measuresModal: {
      title: 'Vyberte typ měření pro vaši zemi',
      close: 'Zavřít',
      oz: 'Imperiální',
      g: 'Metrické',
      tbsp: 'Polévková lžíce',
    },
    timerButton: {
      buttonText: 'Časovač: {duration}'
    },
  }
};
