export const translates = {
    navigation: {
        home: 'Home',
        grocery: 'Search by ingredients',
        recipes: 'Recipes',
        recipe: 'Recipe',
        features: 'Features',
        profile: 'Settings',
        cart: 'Shop cart',
        voice: 'Voice',
        storage: 'Storage',
        subscriptions: 'Community',
        faq: 'FAQ',
        author: 'Chef',
        health: 'Health',
        supplement: 'Supplement',
        authors: 'Gastro Chefs',
    },
    common: {
        close: 'Close',
        hour: 'hour',
        hours: 'hours',
        minute: 'minute',
        minutes: 'minutes',
        second: 'second',
        seconds: 'seconds',
        "easy": "Easy",
        "medium": "Medium",
        "hard": "Hard",
        "g": "g",
        "packs": "packs",
        "pcs": "pcs",
        "oz": "oz",
        "ml": "ml",
        "tbsp": "tbsp",
        "tsp": "tsp",
        "cups": "cups",
        "cloves": "cloves",
        "slices": "slices",
        "package": "packages",
        "pinch": "pinches",
        "sheet": "sheets",
    },
    pages: {
        home: {
            openRecipeButton: 'Open Recipe Steps 🧑🏽‍🍳',
            defaultRecipeTitle: 'Recipe',
            defaultAuthorName: 'Gastro & Me',
            shareMessage: 'I want to share the {title} recipe, ingredients: \n\n{ingredients}',
            shareError: 'Unable to share',
            soundMuted: 'Sound muted',
            soundUnmuted: 'Sound on',
            paused: 'Paused',
            playing: 'Playing',
            videoUnavailable: 'Video unavailable',
            likeAccessibilityLabel: 'Like video',
            likeActionLabel: 'Like',
            stopBackgroundMusic: 'Stop background music',
            startBackgroundMusic: 'Play background music',
            musicActionLabel: 'Music',
            shareAccessibilityLabel: 'Share video',
            shareActionLabel: 'Share',
            feedAll: 'All',
            feedFavorites: 'Favorites',
            favoritesEmptyFeed: "You don't have favorite videos yet",
        },
        authors: {
            emptyList: 'No authors found on platform :(',
            becomeChef: "Become new Chef",
        },
        author: {
            emptyList: 'Author has no recipes :(',
            recipes: 'Recipes (scroll down):',
            title: "Our lovely stars",
        },
        health: {
            benefits: 'Benefits:',
        },
        cart: {
            notFound: 'Now is empty, you could add items from any recipe page',
            notFoundButton: 'Go to Recipes',
            finish: 'Finish shopping',
            addIngredient: 'Add your product ...',
            removeSelectedItem: 'Remove selected items',
            addedToCartTitle: '"{name}" has been added to cart. You can find it in main menu',
            alreadyAdded: '"{name}" already in cart',
            finishShopping: "Shopping is end, thanks you",
            onBoardingTooltip: 'Select all items for end shopping',
            howItWorks: 'Shopping cart \n - How it works -',
            clear: 'Wish to clear whole cart?',
        },
        welcome: {
            tryIt: 'Explore!',
            title: 'New taste, experience, recipes',
            subTitle: 'Try Voice Cooking Assistant on recipe page',
            generator: 'Swipe and get random Recipe',
            all: 'All Recipes 🧑‍🍳',
            supplements: 'Supplements 🫚',
        },
        grocery: {
            startVoice: 'Use voice for detection',
            onBoard: 'Choose ingredients more than 3 items for continue',
            selectText: 'Choose products',
            name: 'Name',
            confirmText: 'Get recipes',
            removeAll: 'Remove all!',
            applyText: 'Apply',
            features: 'Setup your gastro intestinal features',
            yes: 'Yes',
            no: 'No',
            productAdded: 'We were able to identify {count} products:',
            productNotFound: 'Apologize, we have no recognize any ingredient',
            addedIngredient: 'Added "{name}", say next',
            tellUs: 'Tell us what ingredients you have ...',
            search: 'Search here ...',
            notFound: 'Sorry, we can not find something. Please, try again',
            ok: 'Ok',
            howItWorks: 'Search by ingredients \n - How it works -',
            assistantHelpTitle: 'Hands-Free Ingredient Selection',
            assistantHelpTextButton: 'Ok',
            assistantHelpText: 'Just tap the button at the top of the list, and you\'re ready to use your voice to add items from your freezer. Once your done press it again and result will appears!',
        },
        profile: {
            terms: 'Terms of Use',
            privacy: 'Privacy',
            text: 'You have possible to choose your gastro prefer',
            footer: 'Gastro&Me Team Ⓒ 2023',
            chooseNewVoice: 'Hey! Me your new assistant',
            chooseAssistantButton: 'Assistant Voice 🗣',
            confirmText: 'Confirm',
            contact: 'Contact us 📩',
            subscribed: 'Current plan is: {name}',
            firstSeen: 'You with us from: {date}',
            expires: 'Expires: {date}',
            subscriptions: 'Join Community 🌟',
            measure: 'Measure ',
            chooseSubscription: 'Choose plan',
            subscriptionsTitle: 'Subscription',
            howToCancel: 'Manage your subscription',
            cancel: 'Cancel',
            inActiveSubscriberTitle: 'more and more features and platform grow soon 🫡',
            themeTitle: 'Choose app theme',
            // faq: 'About us',
            storage: 'Storage',
            feedback: 'Rate app 🤩',
            join: 'Join Community',
            community: 'GastroMe Community',
            communityText: "Happy to see you in our side, we are growing quick!  \n Chat and Streams soon"
        },
        storage: {
            usedSize: 'Used size - {size} Mb',
            clean: 'Clean',
            sure: 'Sure wanna clean all app files?',
            cleanTitle: 'Storage is clean',
            cleanDescription: 'We has been deleted videos and photos which app keeps',
            ok: 'Ok'
        },
        recipes: {
            get: 'Read more',
            voiceAssistant: 'Ingredients search',
            onBoardingTooltip: 'Try filter by category',
            searchTitle: 'Search by name ...',
            selectedIngredientsTitle: 'You searching by these ingredients',
            selectedIngredients: 'You\'re having:',
            reset: 'Reset',
            emptyList: 'Sorry, we have no appropriate recipes for you',
            hasVideoSteps: 'Includes video instruction',
            filters: 'Filters',
            ingredients: 'Ingredients',
            sort: 'Sorts',
            favorites: 'Saved',
            filtersTitle: 'Select up to 3 categories for filtering recipes: ',
            onBoardingFilter: 'You could find filters here',
            close: 'Close',
            apply: 'Apply',
            subscriptions: 'Prepared plans for your:',
            buySubscription: 'Join GastroMe Community',
            time: '{time} min',
        },
        recipe: {
            madeBy: 'Author Instagram @{name}',
            time: '{time} min',
            step: 'Step {number}.',
            start: 'Start',
            startVoice: 'Start cooking!',
            noLimit: 'Limit of free recipes exhausted',
            limit: 'Left {amount} free recipes',
            addedToCartTitle: '"{name}" has been added to the cart',
            addedToCartText: 'You can found these ingredients in card for make shopping easily',
            cartButton: 'Visit cart',
            level: 'Level',
            region: 'Region',
            author: 'Chef: {name}',
            cartOnBoard: 'Add all ingredients to shopping cart',
            servings: 'Servings: {count} people',
            watchVideo: 'Play video ▶️',
            voiceSelect: 'Choose voice',
            ingredients: 'Ingredients',
            addToCart: 'Press to add all ingredients to shopping list ',
            viewed: 'Viewed',
            proteins: 'Proteins',
            carbs: 'Carbs',
            fats: 'Fats',
            calories: 'Calories',
            chooseMeasure: 'Measures ⚖️',
            freeRecipesToastTitle: 'You have {remaining} of {limit} free recipes left today',
            freeRecipesToastCta: 'Join the community or grab a ticket to watch every recipe',
            freeRecipesBannerTitle: 'Free recipes left today: {remaining} of {limit}',
            freeRecipesBannerSubtitle: 'Unlock the full library without daily limits',
            freeRecipesBannerCta: 'Unlock access',
            commentsTitle: 'Community comments',
            commentsPlaceholder: 'Share your experience with this recipe...',
            commentsSubmit: 'Send',
            commentsEmpty: 'No comments yet. Be the first to share your thoughts!',
            commentsYou: 'You',
            commentsJustNow: 'just now',
        },
        cooking: {
            singleVideo: '(Single video for all steps)',
            step: '- Step {index} of {count} -',
            startVoice: 'Run Assistant',
            assistantCommandsTitle: 'Use commands "next", "back", "repeat" for interact with Voice Assistant',
            start: 'Start',
            loading: 'Downloading video...',
            voiceSelect: 'Voices',
            lastStep: ', Its last step, use command "Done" for end cooking',
            timerEnd: 'Your timer is end',
            nextCommand: 'Wait your command',
            durationCommand: 'For set timer for {duration}, say timer.',
            voiceCommands: 'Commands: next, back, repeat',
            listenText: 'Listening step',
            "next": "next",
            "repeat": "repeat",
            "timer": "timer ⏲️",
            "done": "done",
            back: 'Back',
            backCommand: 'back',
        }
    },
    components: {
        onboard: {
            "firstTitle": "Welcome!",
            "firstSubtitle": "Discover a vast collection of video recipes, create shopping lists, and enjoy the convenience of a voice assistant.",
            "secondTitle": "Shopping List",
            "secondSubtitle": "Easily turn your favorite recipes into a shopping list and share it with just one click!",
            "thirdTitle": "Voice Assistant",
            "thirdSubtitle": "Control video steps hands-free with the help of our voice assistant."
        },
        filters: {
            'breakfast': 'Breakfast',
            'lunch': 'Lunch',
            'dinner': 'Dinner',

            'italy': 'Italy',
            'ukraine': 'Ukraine',

            'pasta': 'Pasta',
            'dessert': 'Dessert',
            'snack': 'Snack',
            'coffee': 'Coffee',
            'salad': 'Salad',
            'favorites': 'Favorites',
            'easy': 'Easy',
            'medium': 'Medium',
            'vegan': 'Vegan',
            'healthy': 'Healthy',
            'drink': 'Drink',
            'roll': 'Rolls',
        },
        autocomplete: {
            applyText: 'Apply',
            removeAll: 'Reset!',
        },
        modal: {
            close: 'Close',
        },
        subscriptionsModal: {
            free: 'Keep free',
            benefits: 'Next 5 free recipes tomorrow \n Unlock:',
            benefitsOne: 'Unlimited recipes 🥘',
            benefitsTwo: 'Color Themes 🎨',
            benefitsThree: 'Ingredient Knowledge 🌿',
            nextFreeRecipesIn: 'Next free recipes in {time}',
            error: 'Sorry, subscription purchase error, try again or contact to us on settings page',
            restore: 'Restore',
            success: 'Thank you for subscribing! Your support fuels our app\'s growth 🚀',
        },
        voicePermission: {
            text: 'Oops!\n\n  AI Assistant require to permission for "Microphone" and "Speech recognition". \n\n  Try to visit setting of the app for turn on it.',
            button: 'Go to settings',
            close: 'Close',
        },
        voiceButton: {
            listenActive: 'Listening...',
            tip: "Voice Assistant Here"
        },
        volumeModal: {
            text: 'Oops! Looks like your volume is low. Increase it to access this feature.',
            tryAgain: 'Try again',
            close: 'Close',
        },
        recipesGenerator: {
            title: 'Random Recipe There:',
            generate: 'Get new',
            time: '{time} min',
        },
        measuresModal: {
            title: 'Choose your country weight type',
            close: 'Close',
            oz: 'Oz',
            g: 'Grams',
            tbsp: 'Table Spoon',
        },
        timerButton: {
            buttonText: 'Timer'
        },
    }
};
