export const translates = {
    navigation: {
        home: 'Welcome',
        grocery: 'Search by ingredients',
        recipes: 'Recipes',
        recipe: 'Recipe',
        features: 'Features',
        profile: 'Settings',
        cart: 'Shop cart',
        voice: 'Voice',
        storage: 'Storage',
        subscriptions: 'Support',
        faq: 'FAQ',
        author: 'Chef',
        authors: 'Gastro Chefs',
    },
    common: {
        close: 'Close',
        hour: 'hour',
        hours: 'hours',
        minute: 'minute',
        minutes: 'minutes',
        second: 'second',
        seconds: 'seconds',
    },
    pages: {
        authors: {
            emptyList: 'No authors found on platform :(',
            becomeChef: "Become new Chef",

        },
        author: {
            emptyList: 'Author has no recipes :(',
            recipes: 'Recipes:',
            title: "Our lovely stars",
        },
        cart: {
            notFound: 'Now is empty, you could add items from any recipe page',
            notFoundButton: 'Go to Recipes',
            finish: 'Finish shopping',
            addIngredient: 'Add your product ...',
            removeSelectedItem: 'Remove selected items',
            addedToCartTitle: '"{name}" has been added to cart. You can find it in main menu',
            alreadyAdded: '"{name}" already in cart',
            finishShopping: "Shopping is end, thanks you",
            onBoardingTooltip: 'Select all items for end shopping',
            howItWorks: 'Shopping cart \n - How it works -',
            clear: 'Wish to clear whole cart?',
        },
        welcome: {
            tryIt: 'Explore!',
            title: 'Begin your improvement cooking journey right from home.',
            subTitle: 'Try AI-powered voice cooking assistant on recipe page',
            generator: 'Swipe and get random Recipe',
        },
        grocery: {
            startVoice: 'Use voice for detection',
            onBoard: 'Choose ingredients more than 3 items for continue',
            selectText: 'Choose products',
            name: 'Name',
            confirmText: 'Get recipes',
            removeAll: 'Remove all!',
            applyText: 'Apply',
            features: 'Setup your gastro intestinal features',
            yes: 'Yes',
            no: 'No',
            productAdded: 'We were able to identify {count} products:',
            productNotFound: 'Apologize, we have no recognize any ingredient',
            addedIngredient: 'Added "{name}", say next',
            tellUs: 'Tell us what ingredients you have ...',
            search: 'Search here ...',
            notFound: 'Sorry, we can not find something. Please, try again',
            ok: 'Ok',
            howItWorks: 'Search by ingredients \n - How it works -',
            assistantHelpTitle: 'Hands-Free Ingredient Selection',
            assistantHelpTextButton: 'Ok',
            assistantHelpText: 'Just tap the button at the top of the list, and you\'re ready to use your voice to add items from your freezer. Once your done press it again and result will appears!',
        },
        profile: {
            terms: 'Terms of Use',
            privacy: 'Privacy',
            text: 'You have possible to choose your gastro prefer',
            footer: 'Gastro&Me Team Ⓒ 2023',
            chooseNewVoice: 'Hey! Me your new assistant',
            chooseAssistantButton: 'Assistant Voice 🗣',
            confirmText: 'Confirm',
            contact: 'Contact us 📩',
            subscribed: 'Current plan is: {name}',
            firstSeen: 'You with us from: {date}',
            expires: 'Expires: {date}',
            subscriptions: 'Join Community 🌟',
            measure: 'Measure ',
            chooseSubscription: 'Choose support plan',
            subscriptionsTitle: 'Subscription',
            howToCancel: 'Manage your subscription',
            cancel: 'Cancel',
            inActiveSubscriberTitle: 'Your support means the world to us 🫡',
            // faq: 'About us',
            storage: 'Storage',
            feedback: 'Rate app 🤩'
        },
        storage: {
            usedSize: 'Used size - {size} Mb',
            clean: 'Clean',
            sure: 'Sure wanna clean all app files?',
            cleanTitle: 'Storage is clean',
            cleanDescription: 'We has been deleted videos and photos which app keeps',
            ok: 'Ok'
        },
        recipes: {
            get: 'Read more',
            voiceAssistant: 'Ingredients search',
            onBoardingTooltip: 'Try filter by category',
            searchTitle: 'Search by name ...',
            selectedIngredientsTitle: 'You searching by these ingredients',
            selectedIngredients: 'You\'re having:',
            reset: 'Reset',
            emptyList: 'Sorry, we have no appropriate recipes for you',
            hasVideoSteps: 'Includes video instruction',
            filters: 'Filters',
            ingredients: 'Ingredients',
            sort: 'Sorts',
            favorites: 'Saved',
            filtersTitle: 'You can select categories for filtering recipes: ',
            onBoardingFilter: 'You could find filters here',
            close: 'Close',
            apply: 'Apply',
            subscriptions: 'Prepared plans for your:',
            buySubscription: 'Join GastroMe Community',
            extraRecipesText: 'You have 8 free monthly recipes,\n do you wish more?',
            time: '{time} min',
        },
        recipe: {
            time: '{time} min',
            step: 'Step {number}.',
            start: 'Start',
            startVoice: 'Start cooking!',
            addedToCartTitle: '"{name}" has been added to the cart',
            addedToCartText: 'You can found these ingredients in card for make shopping easily',
            cartButton: 'Visit cart',
            level: 'Level',
            region: 'Region',
            author: 'Chef: {name}',
            cartOnBoard: 'Add all ingredients to shopping cart',
            servings: 'Servings: {count} people',
            watchVideo: 'Open video steps',
            voiceSelect: 'Choose voice',
            ingredients: 'Ingredients',
            addToCart: 'Press to add all ingredients to shopping list ',
            viewed: 'Viewed',
            chooseMeasure: 'Measure ⚖️',
        },
        cooking: {
            singleVideo: '(Single video for all steps)',
            step: '- Step {index} of {count} -',
            startVoice: 'Cook with Voice assistant',
            assistantCommandsTitle: 'Use commands "next", "back", "repeat" for interact with Voice Assistant',
            start: 'Start',
            madeBy: 'Video Instagram @{name}',
            loading: 'Downloading video...',
            voiceSelect: 'Voices',
            lastStep: ', Its last step, use command "Done" for end cooking',
            timerEnd: 'Your timer is end',
            nextCommand: 'Wait your command',
            durationCommand: 'For set timer for {duration}, say timer.',
            voiceCommands: 'Commands: next, back, repeat or timer',
            listenText: 'Listening step',
            "next": "next",
            "repeat": "repeat",
            "timer": "timer",
            "done": "done",
            back: 'Back',
            backCommand: 'back',
        }
    },
    components: {
        filters: {
            'breakfast': 'Breakfast',
            'lunch': 'Lunch',
            'dinner': 'Dinner',

            'italy': 'Italy',
            'ukraine': 'Ukraine',

            'pasta': 'Pasta',
            'dessert': 'Dessert',
            'snack': 'Snack',
            'coffee': 'Coffee',
            'salad': 'Salad',
        },
        autocomplete: {
            applyText: 'Apply',
            removeAll: 'Reset!',
        },
        modal: {
            close: 'Close',
        },
        subscriptionsModal: {
            free: 'Keep free',
            benefits: 'Exclusive Benefits GastroMe Community:',
            benefitsOne: 'Unlock 30+ recipes 📚',
            benefitsTwo: 'Special environment 🥰',
            benefitsThree: 'Private Streams 🧝',
            error: 'Sorry, subscription purchase error, try again or contact to us on settings page',
            restore: 'Restore',
            success: 'Thank you for subscribing! Your support fuels our app\'s growth 🚀',
        },
        voicePermission: {
            text: 'Oops!\n\n  AI Assistant require to permission for "Microphone" and "Speech recognition". \n\n  Try to visit setting of the app for turn on it.',
            button: 'Go to settings',
            close: 'Close',
        },
        voiceButton: {
            listenActive: 'Listening...',
        },
        volumeModal: {
            text: 'Oops! Looks like your volume is low. Increase it to access this feature.',
            tryAgain: 'Try again',
            close: 'Close',
        },
        recipesGenerator: {
            title: 'Random Recipe There:',
            extraRecipesText: 'There are 8 recipes available to you, for more click on text',
            generate: 'Get new',
            time: '{time} min',
        },
        measuresModal: {
            title: 'Choose your country weight type',
            close: 'Close',
            oz: 'Imperial',
            g: 'Metric',
            tbsp: 'Table Spoon',
        },
        timerButton: {
            buttonText: 'Timer: {duration}'
        },
    }
};
